name: Playwright Tests

on:
  push:
    branches: [ main ]
 
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Test Repository
        uses: actions/checkout@v4

      - name: Clone Web App Repository
        run: git clone https://github.com/mraafayv/qa-automation.git web-app

      - name: Install Dependencies for Web App
        run: |
          cd web-app
          npm ci
          npm run build 

      - name: Start Web App
        run: cd web-app && npm run start &

      - name: Install Playwright Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Upload Playwright Report (if tests fail)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
